[package]
name = "utu_example"
version = "0.1.0"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.8.4"
utils = { git = "https://github.com/keep-starknet-strange/raito.git", rev = "02a13045b7074ae2b3247431cd91f1ad76263fb2" }
consensus = { git = "https://github.com/keep-starknet-strange/raito.git", rev = "02a13045b7074ae2b3247431cd91f1ad76263fb2" }
utu_relay = { git = "https://github.com/lfglabs-dev/utu_relay.git", rev = "9c961ea" }

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.31.0" }
assert_macros = "2.8.4"

[[target.starknet-contract]]
sierra = true
allowed-libfuncs-list.name = "experimental"
build-external-contracts = ["utu_relay::utu_relay::UtuRelay"]

[scripts]
test = "snforge test"
